TestMVCCore/Models/WebOptions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestMVCCore.Models
{
    public class WebOptions
    {
        public WebOptions() { }

        public string Title { get; set; }
    }
}

TestMVCCore/Models/WebUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

namespace TestMVCCore.Models
{
    public class WebUser
    {
        [Required]
        [StringLength(25)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(25)]
        public string LastName { get; set; }

/*      [Required]
        [EmailAddress]
        public string MailAddress { get; set; }

        [Phone]
        public string PhoneNumber { get; set; }

        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Date)]
        public DateTime Birthday { get; set; }

        public bool IsActive { get; set; }

        [MaxLength(10)]
        public string Description { get; set; }*/
        public string Country { get; set; }
    }
}

TestMVCCore/ViewModels/EditUserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestMVCCore.Models;

namespace TestMVCCore.ViewModels
{
    public class EditUserViewModel
    {
        public WebUser User { get; set; }

        public List<string> Countries { get; set; }
    }
}

TestMVCCore/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Diagnostics;

namespace TestMVCCore.Controllers
{
    public class ErrorController : Controller
    {
        public IActionResult Index()
        {
            var exceptionHandlerPathFeature = HttpContext.Features.Get<IExceptionHandlerPathFeature>();
            if ((exceptionHandlerPathFeature != null) && (exceptionHandlerPathFeature.Error != null))
            {
                // In our example, the ExceptionHelper.LogException() method will take care of   
                // logging the exception to the database and perhaps even alerting the webmaster  
                // Make sure that this method doesn't throw any exceptions or you might end  
                // in an endless loop!  
                //ExceptionHelper.LogException(exceptionHandlerPathFeature.Error);
            }
            return Content("We're so sorry, but an error just occurred! We'll try to get it fixed ASAP!");
        }
        public IActionResult Http(int statusCode)
        {
            if (statusCode == 404)
            {
                // Log this error here, e.g. to a database. You can use the HttpContext.Request   
                // object to access important information like the requested URL  
            }
            // Return a View where the problem is explained. It can use the common Layout or not  
            // and you can even make specific views for the types of errors you want to handle,  
            // e.g. Error404.cshtml, as shown here...  
            if (statusCode == 404)
                return View("Error404");
            return View();
        }
    }
}

TestMVCCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using TestMVCCore.Models;
using Microsoft.Extensions.Options;

namespace TestMVCCore.Controllers
{
    public class HomeController : Controller
    {
        /*private readonly IConfiguration _configuration;
        public HomeController(IConfiguration configuration)
        {
            _configuration = configuration;
        }*/
        /*public ActionResult Index()
        {
            //return Content("Welcome to " + _configuration.GetValue<string>("WebsiteTitle"));
            return View();
        }*/
        private WebOptions _webOptions;
        public HomeController(IOptions<WebOptions> websiteOptions)
        {
            this._webOptions = websiteOptions.Value;
        }
        public IActionResult Index()
        {
            return Content("Welcome to " + _webOptions.Title);
        }
    }
}

TestMVCCore/Controllers/QueryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TestMVCCore.Controllers
{
    public class QueryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult QueryTest()
        {
            string name = "John Doe";
            if (!String.IsNullOrEmpty(HttpContext.Request.Query["name"]))
                name = HttpContext.Request.Query["name"];

            return Content("Name from query string: " + name);
        }
        [HttpGet]
        public IActionResult FormsTest()
        {
            return View();
        }

        [HttpPost]
        public IActionResult FormsTestPost()
        {
            return Content("Hello, " + HttpContext.Request.Form["UserName"] + ". You are " + HttpContext.Request.Form["UserAge"] + " years old!");
        }
    }
}

TestMVCCore/Controllers/ValidationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TestMVCCore.Models;
using TestMVCCore.ViewModels;


namespace TestMVCCore.Controllers
{
    public class ValidationController : Controller
    {
        [HttpGet]
        public IActionResult SimpleValidation()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SimpleValidation(WebUser webUser)
        {
            if (ModelState.IsValid)
                return Content("Thank you!");
            else
                return View(webUser);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(WebUser user1)
        {
            if (ModelState.IsValid)
                return Content("Thanks!");
            else
                return View(user1);
        }

        public ViewResult EditUser()
        {
            EditUserViewModel viewModel = new EditUserViewModel();
            viewModel.User = new WebUser()
            {
                FirstName = "John",
                LastName = "Doe",
                Country = "USA"
            };
            viewModel.Countries = new List<string>()
            {
                "USA",
                "Great Britain",
                "Germany"
            };
            return View(viewModel);
        }
    }
}

TestMVCCore/Views/Query/FormsTestPost.cshtml
@{
    ViewData["Title"] = "FormsTestPost";
}

<h1>FormsTestPost</h1>

TestMVCCore/Views/Validation/Create.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers 
@model TestMVCCore.Models.WebUser
@{
    ViewData["Title"] = "Create";
}
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
</head>

<form method="post" asp-controller="Validation" asp-action="Create">
    <div>
        <label asp-for="FirstName"></label><br />
        <input asp-for="FirstName" />
        <span asp-validation-for="FirstName" style="color: red;"></span>
    </div>
    <br />
    <div>
        <label asp-for="LastName"></label><br />
        <input asp-for="LastName" />
        <span asp-validation-for="LastName" style="color: red;"></span>
    </div>
    <br />
    @*<div>
        <label asp-for="MailAddress">Mail Address</label><br />
        <input asp-for="MailAddress" />
        <span asp-validation-for="MailAddress" style="color: red;"></span>
    </div>
    <br />
    <div>
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" />
    </div>
    <div>
        <label asp-for="Password"></label>
        <input asp-for="Password" />
    </div>
    <div>
        <label asp-for="Birthday"></label>
        <input asp-for="Birthday" />
    </div>
    <div>
        <label asp-for="IsActive"></label>
        <input asp-for="IsActive" />
    </div>
    <div>
        <textarea asp-for="Description"></textarea>
    </div>*@
    
    <input type="submit" value="Create" />
</form>

TestMVCCore/Views/Validation/EditUser.cshtml
@model TestMVCCore.ViewModels.EditUserViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<form method="post" asp-controller="Validation" asp-action="EditUser">
    <input asp-for="User.FirstName" placeholder="First name" />
    <input asp-for="User.LastName" placeholder="Last name" />

    <select asp-items="@(new SelectList(Model.Countries))" asp-for="User.Country"></select>

    <input type="submit" value="Save" />
</form>

TestMVCCore/Views/Validation/SimpleValidation.cshtml
@model TestMVCCore.Models.WebUser
@using (var form = Html.BeginForm())
{
    <div>
        @Html.LabelFor(m => m.FirstName)
        @Html.TextBoxFor(m => m.FirstName)
        @Html.ValidationMessageFor(m => m.FirstName)
    </div>

    <div>
        @Html.LabelFor(m => m.LastName)
        @Html.TextBoxFor(m => m.LastName)
        @Html.ValidationMessageFor(m => m.LastName)
    </div>

    @*<div>
        @Html.LabelFor(m => m.MailAddress)
        @Html.TextBoxFor(m => m.MailAddress)
        @Html.ValidationMessageFor(m => m.MailAddress)
    </div>*@

    <input type="submit" value="Submit"/>
}